modules/admin/controllers/MenuController.php
<?php

namespace app\modules\admin\controllers;

use \app\models\search\TestQuestionSearch;
use app\models\Calories;
use app\models\Content;
use app\models\ContentHasImage;
use app\models\MenuHasUser;
use app\models\search\ContentSeacrch;
use app\models\search\UserSearch;
use app\models\TestQuestion;
use creocoder\nestedsets\NestedSetsBehavior;
use Yii;
use app\models\Menu;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MenuController implements the CRUD actions for Menu model.
 */
class MenuController extends Controller
{

    public function actions()
    {
        return [
            'nodeMove' => [
                'class' => 'klisl\nestable\NodeMoveAction',
                'modelName' => Menu::class,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Menu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $root = Menu::find()->where(['depth' => '0']);
        return $this->render('index', [
            'query' => $root,
        ]);
    }

    /**
     * Displays a single Menu model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Menu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        /** @var  $model Menu|NestedSetsBehavior */
        $modelDup = Menu::find()->where(['LIKE', 'name', '%' . $_POST['Menu']['name'] . '%', false])->all();
        $model = new Menu ();
        //Поиск корневого элемента
        $root = $model->find()->where(['depth' => '0'])->one();
        if ($model->load(Yii::$app->request->post())) {
            if (!empty($modelDup)) {
                $model->name = $model->name . '-' . count($modelDup);
            }
            //Если нет корневого элемента (пустая таблица)
            $model->appendTo($root); //вставляем в конец корневого элемента
            if ($model->save()) {
                if (isset($_POST['roles']) && !empty($_POST['roles'])) {
                    foreach ($_POST['roles'] as $role) {
                        $MHU = new MenuHasUser();
                        $MHU->role = $role;
                        $MHU->menu_id = $model->id;
                        $MHU->save(false);
                    }
                }
                return $this->redirect('index');
            }
        }

        return $this->render('create', [
            'model' => $model,
            'root' => $root
        ]);
    }

    /**
     * Updates an existing Menu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            MenuHasUser::deleteAll(['menu_id' => $model->id]);
            foreach ($_POST['roles'] as $role) {
                $mhu = new MenuHasUser();
                $mhu->menu_id = $model->id;
                $mhu->role = $role;
                $mhu->save(false);
            }
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Menu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Menu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Menu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Menu::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionCategory()
    {
        /**
         * @var $model Menu
         */
        $model = Content::menuSearch();
        if ($model->design_id == 7) {
            $searchModel = new TestQuestionSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            return $this->render('tests/index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'model' => $model
            ]);
        }
        $searchModel = new ContentSeacrch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('category-content/category', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreateCategoryContent()
    {
        $menu = Content::menuSearch();
        $model = new Content();
        if ($menu->design_id == 7) {
            $model = new TestQuestion();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save() && $this->saveFile($model)) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('category-content/create', [
            'model' => $model,
            'menu' => $menu,
        ]);

    }

    public function actionUpdateCategoryContent()
    {

        $menu = Content::menuSearch();
        if ($menu->design_id == 7) {
            $model = TestQuestion::findOne($_GET['id']);
        } else {
            $model = Content::findOne($_GET['id']);
        }
        if ($model->load(Yii::$app->request->post()) && $this->saveFile($model) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('category-content/update', [
            'model' => $model,
            'menu' => $menu,
        ]);

    }

    public function actionDeleteCategoryContent()
    {
        $model = Content::findOne(['id' => $_GET['id']]);
        if ($model->delete()) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function saveFile($model)
    {

        $menu = Content::menuSearch();

        $dir = Yii::getAlias('@webroot/uploads/' . $menu->id . '/');
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }
        $files = UploadedFile::getInstances($model, 'img');
        $file_avatar = UploadedFile::getInstance($model, 'img2');
        if (!empty($files)) {
            foreach ($files as $file) {
                $withoutExt = preg_replace('/\\.[^.\\s]{3,4}$/', '', $file->name);
                $imgModel = new ContentHasImage();
                $imgModel->content_id = $model->id;
                $imgModel->title = $withoutExt;
                $fname = uniqid("", true) . '.' . $file->extension;
                $imgModel->name = $fname;
                $imgModel->save(false);
                $file->saveAs($dir . $fname);
            }
        }
        if ($file_avatar) {
            $fname = uniqid("", true) . '.' . $file_avatar->extension;
            $model->image = $fname;
            $model->save(false);
            $file_avatar->saveAs($dir . $fname);
        }

        return true;
    }

    public function actionDeleteImage()
    {
        $model = ContentHasImage::findOne($_POST['key']);
        $dir = Yii::getAlias('@webroot/uploads/' . $_GET['category'] . '/');
        unlink($dir . $model->name);
        $model->name = null;
        return json_encode($model->delete());
    }

    public function actionDeleteImageAvatar()
    {
        $model = Content::findOne($_POST['key']);
        $dir = Yii::getAlias('@webroot/uploads/' . $_GET['category'] . '/');
        unlink($dir . $model->image);
        $model->image = null;
        return json_encode($model->save(false));
    }

}

modules/admin/views/menu/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Menu */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="menu-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'points')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'design_id')->dropDownList(\app\models\Content::$design_ids) ?>
    <?= $form->field($model, 'is_news')->checkbox() ?>
    <label>Роль в какой будет виден раздел</label>
    <?php
    echo Select2::widget([
        'name' => 'roles',
        'value' => \yii\helpers\ArrayHelper::map($model->contentRoles, 'id', 'role'),
        'data' => \app\models\User::$roles,
        'theme' => Select2::THEME_DEFAULT,
        'options' => ['placeholder' => 'Выбрать роль ...', 'multiple' => true, 'autocomplete' => 'off'],
        'pluginOptions' => [
            'allowClear' => false
        ],
    ]);
    ?>
    <div class="form-group" style="margin-top:20px">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/menu/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\MenuSeacrch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="menu-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'lft') ?>

    <?= $form->field($model, 'rgt') ?>

    <?= $form->field($model, 'depth') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/menu/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Menu */

$this->title = 'Создание нового раздела';
$this->params['breadcrumbs'][] = ['label' => 'Меню', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="menu-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/menu/index.php
<?php

use yii\helpers\Html;
use klisl\nestable\Nestable;
use yii\helpers\Url;

/* @var $query \yii\db\ActiveQuery */

$this->title = 'Меню сайта';
$this->params['breadcrumbs'][] = $this->title;
?>
<div id="nestable-menu">
    <button class="btn btn-default" type="button" data-action="expand-all">Развернуть</button>
    <button class="btn btn-default" type="button" data-action="collapse-all">Свернуть</button>
</div>

<div class="menu-index">

    <p><?= Html::a('Создать новый раздел', ['create'], ['class' => 'btn btn-default']) ?></p>

    <?= Nestable::widget([
        'type' => Nestable::TYPE_WITH_HANDLE,
        'query' => $query,
        'modelOptions' => [
            'name' => function ($model) {
                return $model->name . ' - ' . $model->url;
            }, //поле из БД с названием элемента (отображается в дереве)
        ],
        'pluginEvents' => [
            'change' => 'function(e) {}', //js событие при выборе элемента
        ],
        'pluginOptions' => [
            'maxDepth' => 10,//максимальное кол-во уровней вложенности

            'collapseAll' => 'collapseAll',
        ],
        'update' => Url::to(['menu/update']), //действие по обновлению
        'delete' => Url::to(['menu/delete']), //действие по удалению
        'viewItem' => Url::to(['menu/view']), //действие по удалению
    ]);
    ?>
</div>

modules/admin/views/menu/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Menu */

$this->title = 'Редактирование раздела: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="menu-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/menu/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Menu */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="menu-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'lft',
            'rgt',
            'depth',
            'name',
        ],
    ]) ?>

</div>