modules/admin/controllers/MenuController.php
<?php

namespace app\modules\admin\controllers;

use \app\models\search\TestQuestionSearch;
use app\models\Calories;
use app\models\Content;
use app\models\ContentHasImage;
use app\models\MenuHasUser;
use app\models\search\ContentSeacrch;
use app\models\search\UserSearch;
use app\models\TestQuestion;
use creocoder\nestedsets\NestedSetsBehavior;
use Yii;
use app\models\Menu;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * MenuController implements the CRUD actions for Menu model.
 */
class MenuController extends Controller
{

    public function actions()
    {
        return [
            'nodeMove' => [
                'class' => 'klisl\nestable\NodeMoveAction',
                'modelName' => Menu::class,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Menu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $root = Menu::find()->where(['depth' => '0']);
        return $this->render('index', [
            'query' => $root,
        ]);
    }

    /**
     * Displays a single Menu model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Menu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        /** @var  $model Menu|NestedSetsBehavior */
        $modelDup = Menu::find()->where(['LIKE', 'name', '%' . $_POST['Menu']['name'] . '%', false])->all();
        $model = new Menu ();
        //Поиск корневого элемента
        $root = $model->find()->where(['depth' => '0'])->one();
        if ($model->load(Yii::$app->request->post())) {
            if (!empty($modelDup)) {
                $model->name = $model->name . '-' . count($modelDup);
            }
            //Если нет корневого элемента (пустая таблица)
            $model->appendTo($root); //вставляем в конец корневого элемента
            if ($model->save()) {
                if (isset($_POST['roles']) && !empty($_POST['roles'])) {
                    foreach ($_POST['roles'] as $role) {
                        $MHU = new MenuHasUser();
                        $MHU->role = $role;
                        $MHU->menu_id = $model->id;
                        $MHU->save(false);
                    }
                }
                return $this->redirect('index');
            }
        }

        return $this->render('create', [
            'model' => $model,
            'root' => $root
        ]);
    }

    /**
     * Updates an existing Menu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            MenuHasUser::deleteAll(['menu_id' => $model->id]);
            foreach ($_POST['roles'] as $role) {
                $mhu = new MenuHasUser();
                $mhu->menu_id = $model->id;
                $mhu->role = $role;
                $mhu->save(false);
            }
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Menu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Menu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Menu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Menu::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionCategory()
    {
        /**
         * @var $model Menu
         */
        $model = Content::menuSearch();
        if ($model->design_id == 7) {
            $searchModel = new TestQuestionSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
            return $this->render('tests/index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'model' => $model
            ]);
        }
        $searchModel = new ContentSeacrch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('category-content/category', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreateCategoryContent()
    {
        $menu = Content::menuSearch();
        $model = new Content();
        if ($menu->design_id == 7) {
            $model = new TestQuestion();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save() && $this->saveFile($model)) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('category-content/create', [
            'model' => $model,
            'menu' => $menu,
        ]);

    }

    public function actionUpdateCategoryContent()
    {

        $menu = Content::menuSearch();
        if ($menu->design_id == 7) {
            $model = TestQuestion::findOne($_GET['id']);
        } else {
            $model = Content::findOne($_GET['id']);
        }
        if ($model->load(Yii::$app->request->post()) && $this->saveFile($model) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(Yii::$app->request->referrer);
        }
        return $this->render('category-content/update', [
            'model' => $model,
            'menu' => $menu,
        ]);

    }

    public function actionDeleteCategoryContent()
    {
        $model = Content::findOne(['id' => $_GET['id']]);
        if ($model->delete()) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function saveFile($model)
    {

        $menu = Content::menuSearch();

        $dir = Yii::getAlias('@webroot/uploads/' . $menu->id . '/');
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }
        $files = UploadedFile::getInstances($model, 'img');
        $file_avatar = UploadedFile::getInstance($model, 'img2');
        if (!empty($files)) {
            foreach ($files as $file) {
                $withoutExt = preg_replace('/\\.[^.\\s]{3,4}$/', '', $file->name);
                $imgModel = new ContentHasImage();
                $imgModel->content_id = $model->id;
                $imgModel->title = $withoutExt;
                $fname = uniqid("", true) . '.' . $file->extension;
                $imgModel->name = $fname;
                $imgModel->save(false);
                $file->saveAs($dir . $fname);
            }
        }
        if ($file_avatar) {
            $fname = uniqid("", true) . '.' . $file_avatar->extension;
            $model->image = $fname;
            $model->save(false);
            $file_avatar->saveAs($dir . $fname);
        }

        return true;
    }

    public function actionDeleteImage()
    {
        $model = ContentHasImage::findOne($_POST['key']);
        $dir = Yii::getAlias('@webroot/uploads/' . $_GET['category'] . '/');
        unlink($dir . $model->name);
        $model->name = null;
        return json_encode($model->delete());
    }

    public function actionDeleteImageAvatar()
    {
        $model = Content::findOne($_POST['key']);
        $dir = Yii::getAlias('@webroot/uploads/' . $_GET['category'] . '/');
        unlink($dir . $model->image);
        $model->image = null;
        return json_encode($model->save(false));
    }

}

modules/admin/controllers/UserController.php
<?php

namespace app\modules\admin\controllers;

use app\helpers\My;
use app\models\Calories;
use app\models\ContentHasImage;
use app\models\forms\UserView;
use app\models\GroupMember;
use app\models\PaymentLer;
use Yii;
use app\models\User;
use app\models\search\UserSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->getUser()->getIsGuest() || Yii::$app->getUser()->identity->role != User::ROLE_ADMIN) {
            return $this->redirect('/')->send();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $this->saveFile($model) && $model->save(false)) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(['index']);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new User;
        if ($model->load(Yii::$app->request->post()) && $model->save(false) && $this->saveFile($model)) {
            Yii::$app->session->setFlash('success', 'Успешно!');
            return $this->redirect(['index']);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $model->delete();
        Yii::$app->session->setFlash('success', 'Успешно удален!');
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function saveFile($model)
    {
        $dir = Yii::getAlias('@webroot/uploads/users/');
        if (!file_exists($dir)) {
            mkdir($dir, 0777, true);
        }
        $file_avatar = UploadedFile::getInstance($model, 'img');
        if ($file_avatar) {
            $fname = uniqid("", true) . '.' . $file_avatar->extension;
            $model->avatar = $fname;
            $model->save(false);
            $file_avatar->saveAs($dir . $fname);
        }

        return true;
    }

}

modules/admin/views/layouts/content.php
<?php

use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section
            class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            ['links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>
<!-- Control Sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

modules/admin/views/layouts/header.php
<?php

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>
<?php
$user = Yii::$app->user->getIdentity();
?>
<header class="main-header">

    <?= Html::a('<span class="logo-mini">academy</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">


                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?= $user->email ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle"
                                 alt="User Image"/>

                            <p>
                                Администратор и куратор личного кабинета
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Профиль</a>
                            </div>
                            <div class="pull-right">
                                <?= Html::a(
                                    'Выход',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>

                <!-- User Account: style can be found in dropdown.less -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

modules/admin/views/layouts/left.php
<?php

use \app\models\Content;
use app\models\Menu;

$email = Yii::$app->user->getIdentity()->email;
$data = Menu::getItemsMenuAdmin();
?>
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= $email ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
                'items' => [
                    ['label' => Yii::$app->user->identity->email, 'options' => ['class' => 'header pulse']],
                    ['label' => 'Новые участники', 'url' => ['user/index'], 'icon' => 'users', 'active' => Yii::$app->controller->id == 'user' ? true : false],
                    ['label' => 'Создать меню', 'url' => ['menu/index'], 'icon' => 'users', 'active' => Yii::$app->controller->id == 'menu' && !stristr(Yii::$app->controller->action->id, 'category') ? true : false],

                ],
            ]
        ) ?>
        <?= \startpl\yii2NestedSetsMenu\Menu::widget(
            [
                'items' => \startpl\yii2NestedSetsMenu\services\MenuArray::getData($data), // $data is your models|rows
                'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
                'encodeLabels' => false,
                'activateParents' => true,
                'activeCssClass' => 'active',
            ]
        ) ?>

    </section>

</aside>

modules/admin/views/layouts/main.php
<?php

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
app\assets\AppAsset::register($this);
dmstr\web\AdminLteAsset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>

    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-black sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

    <?= $this->render(
        'header.php',
        ['directoryAsset' => $directoryAsset]
    ) ?>

    <?= $this->render(
        'left.php',
        ['directoryAsset' => $directoryAsset]
    )
    ?>

    <?= $this->render(
        'content.php',
        ['content' => $content, 'directoryAsset' => $directoryAsset]
    ) ?>

</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>